---
kind: Service
apiVersion: v1
metadata:
  name: todo-service
  labels:
    app: todo
spec:
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: volaka/meetup-todoapp:3
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb+srv://volaka:3L0yDHK7@todo-app-db-pajlo.mongodb.net/test?retryWrites=true"
        - name: NODE_ENV
          value: production
